/// Updated at 03/19/2021 13:48:13
Class sp.NewClass8 Extends %Persistent [ Language = objectscript ]
{

Storage Default
{
<Data name="NewClass8DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^sp.NewClass8D</DataLocation>
<DefaultData>NewClass8DefaultData</DefaultData>
<IdLocation>^sp.NewClass8D</IdLocation>
<IndexLocation>^sp.NewClass8I</IndexLocation>
<StreamLocation>^sp.NewClass8S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}

